import type { LabValueCategory } from "./exam-types";

export const labValuesData: LabValueCategory[] = [
  {
    id: "cbc",
    name: "Complete Blood Count (CBC)",
    values: [
      { name: "WBC", unit: "×10³/µL", reference_range: "4.5–11.0" },
      { name: "RBC (male)", unit: "×10⁶/µL", reference_range: "4.7–6.1" },
      { name: "RBC (female)", unit: "×10⁶/µL", reference_range: "4.2–5.4" },
      { name: "Hemoglobin (male)", unit: "g/dL", reference_range: "13.5–17.5" },
      { name: "Hemoglobin (female)", unit: "g/dL", reference_range: "12.0–16.0" },
      { name: "Hematocrit (male)", unit: "%", reference_range: "38.3–48.6" },
      { name: "Hematocrit (female)", unit: "%", reference_range: "35.5–44.9" },
      { name: "MCV", unit: "fL", reference_range: "80–100" },
      { name: "MCH", unit: "pg", reference_range: "27–33" },
      { name: "MCHC", unit: "g/dL", reference_range: "32–36" },
      { name: "RDW", unit: "%", reference_range: "11.5–14.5" },
      { name: "Platelets", unit: "×10³/µL", reference_range: "150–400" },
      { name: "Reticulocyte count", unit: "%", reference_range: "0.5–2.5" },
      { name: "Neutrophils", unit: "%", reference_range: "40–70" },
      { name: "Lymphocytes", unit: "%", reference_range: "20–40" },
      { name: "Monocytes", unit: "%", reference_range: "2–8" },
      { name: "Eosinophils", unit: "%", reference_range: "1–4" },
      { name: "Basophils", unit: "%", reference_range: "0–1" },
    ],
  },
  {
    id: "bmp",
    name: "Basic Metabolic Panel (BMP)",
    values: [
      { name: "Sodium (Na⁺)", unit: "mEq/L", reference_range: "136–145" },
      { name: "Potassium (K⁺)", unit: "mEq/L", reference_range: "3.5–5.0" },
      { name: "Chloride (Cl⁻)", unit: "mEq/L", reference_range: "98–106" },
      { name: "Bicarbonate (HCO₃⁻)", unit: "mEq/L", reference_range: "22–28" },
      { name: "BUN", unit: "mg/dL", reference_range: "7–20" },
      { name: "Creatinine", unit: "mg/dL", reference_range: "0.7–1.3" },
      { name: "Glucose (fasting)", unit: "mg/dL", reference_range: "70–100" },
      { name: "Calcium", unit: "mg/dL", reference_range: "8.5–10.5" },
    ],
  },
  {
    id: "cmp",
    name: "Comprehensive Metabolic Panel (CMP)",
    values: [
      { name: "Albumin", unit: "g/dL", reference_range: "3.5–5.5" },
      { name: "Total protein", unit: "g/dL", reference_range: "6.0–8.3" },
      { name: "ALP", unit: "U/L", reference_range: "44–147" },
      { name: "ALT (SGPT)", unit: "U/L", reference_range: "7–56" },
      { name: "AST (SGOT)", unit: "U/L", reference_range: "10–40" },
      { name: "Total bilirubin", unit: "mg/dL", reference_range: "0.1–1.2" },
      { name: "Direct bilirubin", unit: "mg/dL", reference_range: "0.0–0.3" },
    ],
  },
  {
    id: "coag",
    name: "Coagulation",
    values: [
      { name: "PT", unit: "seconds", reference_range: "11–13.5" },
      { name: "INR", unit: "", reference_range: "0.8–1.1" },
      { name: "aPTT", unit: "seconds", reference_range: "25–35" },
      { name: "Fibrinogen", unit: "mg/dL", reference_range: "200–400" },
      { name: "D-dimer", unit: "µg/mL", reference_range: "<0.5" },
      { name: "Bleeding time", unit: "minutes", reference_range: "2–7" },
    ],
  },
  {
    id: "abg",
    name: "Arterial Blood Gas (ABG)",
    values: [
      { name: "pH", unit: "", reference_range: "7.35–7.45" },
      { name: "PaCO₂", unit: "mmHg", reference_range: "35–45" },
      { name: "PaO₂", unit: "mmHg", reference_range: "80–100" },
      { name: "HCO₃⁻", unit: "mEq/L", reference_range: "22–26" },
      { name: "SaO₂", unit: "%", reference_range: "95–100" },
    ],
  },
  {
    id: "thyroid",
    name: "Thyroid",
    values: [
      { name: "TSH", unit: "mIU/L", reference_range: "0.5–5.0" },
      { name: "Free T4", unit: "ng/dL", reference_range: "0.7–1.9" },
      { name: "Free T3", unit: "pg/mL", reference_range: "2.0–4.4" },
      { name: "Total T4", unit: "µg/dL", reference_range: "5.0–12.0" },
      { name: "Total T3", unit: "ng/dL", reference_range: "80–200" },
    ],
  },
  {
    id: "lipids",
    name: "Lipid Panel",
    values: [
      { name: "Total cholesterol", unit: "mg/dL", reference_range: "<200" },
      { name: "LDL", unit: "mg/dL", reference_range: "<100" },
      { name: "HDL", unit: "mg/dL", reference_range: ">40" },
      { name: "Triglycerides", unit: "mg/dL", reference_range: "<150" },
    ],
  },
  {
    id: "urine",
    name: "Urinalysis",
    values: [
      { name: "Specific gravity", unit: "", reference_range: "1.005–1.030" },
      { name: "pH", unit: "", reference_range: "4.5–8.0" },
      { name: "Protein", unit: "", reference_range: "Negative" },
      { name: "Glucose", unit: "", reference_range: "Negative" },
      { name: "Ketones", unit: "", reference_range: "Negative" },
      { name: "Blood", unit: "", reference_range: "Negative" },
      { name: "WBC", unit: "/hpf", reference_range: "0–5" },
      { name: "RBC", unit: "/hpf", reference_range: "0–3" },
    ],
  },
  {
    id: "iron",
    name: "Iron Studies",
    values: [
      { name: "Serum iron", unit: "µg/dL", reference_range: "60–170" },
      { name: "TIBC", unit: "µg/dL", reference_range: "250–370" },
      { name: "Ferritin (male)", unit: "ng/mL", reference_range: "20–250" },
      { name: "Ferritin (female)", unit: "ng/mL", reference_range: "10–120" },
      { name: "Transferrin saturation", unit: "%", reference_range: "20–50" },
    ],
  },
  {
    id: "cardiac",
    name: "Cardiac Markers",
    values: [
      { name: "Troponin I", unit: "ng/mL", reference_range: "<0.04" },
      { name: "CK-MB", unit: "ng/mL", reference_range: "<5" },
      { name: "BNP", unit: "pg/mL", reference_range: "<100" },
      { name: "NT-proBNP", unit: "pg/mL", reference_range: "<300" },
      { name: "LDH", unit: "U/L", reference_range: "140–280" },
    ],
  },
];
